name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: Vampire/setup-wsl@v5
      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install, test
        run: |
          pnpm install
          pnpm add concurrently
          pnpm concurrently "pnpm test" "pnpm typecheck" "pnpm lint"
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_REGION: eu-central-1
          WEBSOCKET_URL: ws://localhost:4321
          LOCAL_DIR: unused
          PORT: 4321